# Generated by Django 3.2.9 on 2021-12-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliar', '0002_conyuge_casada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hijos',
            name='esIntelligente',
            field=models.BooleanField(default=False),
        ),
    ]
